# install with:
# conda env create -f kaggle_hernes.yml
#
# update with:
# conda env update -f kaggle_hernes.yml

name: kaggle_hernes
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9.*
  - pytorch>=1.10,<2.0
  - torchvision>=0.11
  - cudatoolkit=11.*
  - scikit-learn>=1.0,<2.0
  - black
  - flake8
  - numpy>=1.21,<2.0
  - pandas>=1.3,<2.0
  - ipykernel=6.5.0
  - ipywidgets=7.6.5
  - tqdm
  - rapidfuzz
  - pillow=8.4.*
  - python-dotenv
  - scikit-image
  - matplotlib
  - seaborn
  - pip
  - pip:
      - xgboost==1.5.0
      - catboost
